name: dataset-frictionless
on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  jest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: |
          cd examples/dataset-frictionless
          yarn
    
      - name: Run tests
        run: |
          cd examples/dataset-frictionless
          yarn test -u
